### ISSUE TITLE
Time tool improvement

### ISSUE THREAD

**Issue by egaltier** [pcdshub/mec#10]
**Feature Request**

Add the time compensation at the time tool delay stage when changing the pump-probe delay between x-rays and optical laser.

**Existing Alternatives**

Do this manually on the delay stage itself. Can make mistakes and slow down operation.

**Context**

I don't have all the time I wanted to write a more detailed request but this should be fairly straightforward. The time tool is used to measure the arrival time jitter between the xrays and the optical laser. However, when the delay between the pump and the probe is changed, this also change the time tool delay since it is slaved to the optical laser itself. As a result, a delay stage is implemented in the optical beampath of the time tool which is used to compensate the delay introduced at TCC. It means that when pushing a delay value on the VITARA target time, we should move a this stage to compensate this delay by a specific amount and direction. The motor to consider is `MEC:LAS:MMN:19`from the Newport controller `XPS_3 (TimeTool): mcn-mec-las3`.

For example, when the target time on the VITARA is moved negative (moving the optical laser earlier than the `t0`) by say `t=1 ps`, the delay stage should be moved in order to lengthen the beam path to catch back the Xrays in the viewing window. Since the delay stage has a 'trombone' of mirrors (2 mirrors at 90° from each other), it means that when the stage moves by a distance `d` negative (the orientation of the stage and the settings of its direction are set such that going positive shorten the beam path), it will lengthen the beam path and increase the arrival time by the value `t*c/2` with `c` is the speed of light. When adding the units, `d = (t * (2.99792458e8 * 1.e3))/2.` with `t` given in `s` and `c` has been converted to provide `d` in mm, the units directly input to the stage. So, for `t = +1ps`, the delay stage needs to move by `-0.15 mm` to compensate for the delay. When the delay introduced in the fstiming function is negative, say `t = -2ps`, the delay stage needs to move by `+0.3 mm`.

In the command used to change the VITARA timing (`fstiming.mv()`), we need to add the line that compute the change in position on the stage (with the equation described above), and then push the value to the stage. We can directly use the input value given to the command, but the value needs to be converted to provide second `s` for the distance calculation. These few lines could also be added to the `fstiming.mvr()` but since we use this function mainly to find the `t0`, which could be initially off by `ns`, we should not move the delay stage at the same time. So I would not add these lines to the `fstiming.mvr()` function.

**Comment by silkenelson** [comment]
In XPP/XCS, we cann 'fstiming' 'lxt' and already have a compensation object that will compensate when it can. The Newport 'compensation' motor is called 'txt' and the combined stage is 'lxt_ttc'. We e.g. always scan 'txt' for our time tool calibration data. It also comes with a PV that we write on moves though for the fstiming stage this is somewhat less crucial than for other virtual motors. @egaltier , can you maybe talk to Tim (van Driehl)/Diliing/Takahiro so that you can see if you really need the same solution and maybe even decide on a common name for this functionality/'motor'? I would prefer to keep the XPP/XCS naming convention as we save the names in the data for scans and I have years of data using that naming convention, but this is a preference and not a need.
